version: "3.8"

x-mongo-creds: &mongo-creds
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_INITDB_DATABASE: simpleblog

services:
  mongodb:
    image: mongo:7
    container_name: Nook
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      <<: *mongo-creds
    volumes:
      - nook_mongo_data_v2:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - Nook-Network
    pull_policy: never

  redis:
    image: redis:7-alpine
    container_name: Nook-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - Nook-Network
    pull_policy: never

volumes:
  nook_mongo_data_v2:
  redis_data:

networks:
  Nook-Network:
    driver: bridge
